/* bancode_all.h - BANcode Framework master header */
/* AUTO-GENERATED by generate_bindings.py - DO NOT EDIT */
#ifndef BANCODE_ALL_H
#define BANCODE_ALL_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef uint32_t bancode_t;

#define BANCODE_VERSION_MAJOR 1
#define BANCODE_VERSION_MINOR 0
#define BANCODE_VERSION_PATCH 0

#define BANCODE_BANCODE_START  0x0011A000U
#define BANCODE_BANCODE_END    0x0011A7FFU
#define BANCODE_WARNCODE_START  0x0011A800U
#define BANCODE_WARNCODE_END    0x0011ABFFU
#define BANCODE_COMCODE_START  0x0011AC00U
#define BANCODE_COMCODE_END    0x0011ADFFU
#define BANCODE_SOFTCODE_START  0x0011AE00U
#define BANCODE_SOFTCODE_END    0x0011AEFFU


#include "bancode.h"
#include "warncode.h"
#include "comcode.h"
#include "softcode.h"

#define BANCODE_TOTAL_ASSIGNED 0

/* Trap range dispatch - like Unicode surrogate pairs */
/* Each trap address 0x7FFFFFF0+N maps to BANcode at offset N */
#define BANCODE_TRAP_RANGE_START  0x7FFFFFF0U
#define BANCODE_TRAP_RANGE_END    0x7FFFFFFEU
#define BANCODE_TRAP_RANGE_COUNT  15U

/* Convert trap address to BANcode offset (0-based within trap range) */
#define BANCODE_TRAP_TO_OFFSET(trap_addr)  ((trap_addr) - BANCODE_TRAP_RANGE_START)

/* Convert trap offset to BANcode value (adds bancode block base) */
#define BANCODE_OFFSET_TO_CODE(offset)  (0x0011A000U + (offset))

/* Convert trap address directly to BANcode value */
#define BANCODE_TRAP_TO_CODE(trap_addr)  (BANCODE_OFFSET_TO_CODE(BANCODE_TRAP_TO_OFFSET(trap_addr)))

/* Returns true if address is within the trap dispatch range */
#define BANCODE_IS_TRAP_RANGE(addr)  ((addr) >= BANCODE_TRAP_RANGE_START && (addr) <= BANCODE_TRAP_RANGE_END)

/* Returns true if code is a known BANcode */
bool bancode_is_valid(bancode_t code);

/* Returns codename string ("UNKNOWN" if not assigned) */
const char* bancode_name(bancode_t code);

/* Returns description string ("" if not assigned) */
const char* bancode_desc(bancode_t code);

/* Returns category string ("" if not assigned) */
const char* bancode_category(bancode_t code);

#endif /* BANCODE_ALL_H */
