//! BANcode Framework - Rust bindings
//! AUTO-GENERATED by generate_bindings.py - DO NOT EDIT

#![no_std]

use core::fmt;

/// Unrecoverable critical panics, hardware faults, fatal exceptions. May be printable; useful when showing the glyph of the error, not just its codename or codepoint.
/// Range: 0x0011A000 - 0x0011A7FF
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u32)]
pub enum BANcode {
}

impl fmt::Display for BANcode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match *self {
        }
    }
}

impl TryFrom<u32> for BANcode {
    type Error = u32;
    fn try_from(v: u32) -> Result<Self, u32> {
    match v {
            _ => Err(v),
        }
    }
}

/// Non-fatal telemetry; threshold alerts, degraded performance, predictive maintenance. May be printable; useful when showing the glyph of the error, not just its codename or codepoint.
/// Range: 0x0011A800 - 0x0011ABFF
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u32)]
pub enum WARNcode {
}

impl fmt::Display for WARNcode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match *self {
        }
    }
}

impl TryFrom<u32> for WARNcode {
    type Error = u32;
    fn try_from(v: u32) -> Result<Self, u32> {
    match v {
            _ => Err(v),
        }
    }
}

/// IPC events, bus orchestration, hardware handshakes, driver attachment, control plane signals; also success reports. May be printable; useful when showing the glyph of the error, not just its codename or codepoint.
/// Range: 0x0011AC00 - 0x0011ADFF
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u32)]
pub enum COMcode {
}

impl fmt::Display for COMcode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match *self {
        }
    }
}

impl TryFrom<u32> for COMcode {
    type Error = u32;
    fn try_from(v: u32) -> Result<Self, u32> {
    match v {
            _ => Err(v),
        }
    }
}

/// Soft recovery, fault containment, cache reconciliation, self-healing routines; also soft errors. May be printable; useful when showing the glyph of the error, not just its codename or codepoint.
/// Range: 0x0011AE00 - 0x0011AEFF
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u32)]
pub enum SOFTcode {
}

impl fmt::Display for SOFTcode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match *self {
        }
    }
}

impl TryFrom<u32> for SOFTcode {
    type Error = u32;
    fn try_from(v: u32) -> Result<Self, u32> {
    match v {
            _ => Err(v),
        }
    }
}

/// All BANcode diagnostic codes
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u32)]
pub enum BANcode {
}

impl fmt::Display for BANcode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
    match *self {
        }
    }
}

impl TryFrom<u32> for BANcode {
    type Error = u32;
    fn try_from(v: u32) -> Result<Self, u32> {
        match v {
            _ => Err(v),
        }
    }
}

/// Returns true if code is a known BANcode
pub fn is_valid(code: u32) -> bool {
    BANcode::try_from(code).is_ok()
}

/// Returns codename string if known
pub fn name(code: u32) -> Option<&'static str> {
    match code {
        _ => None,
    }
}
