#!/usr/bin/env python3
"""generate_bindings.py - Generate C99 freestanding, Rust, and Python bindings from master_registry.json.

Outputs:
    kernel_inc/bancode/*.h  - C99 freestanding headers
    kernel_src/bancode/*.c  - C99 freestanding sources
    rust_bindings/src/*.rs  - #[no_std] Rust crate
    python/bancode/*.py     - Python IntEnum package
"""

import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
REGISTRY = DATA_DIR / "master_registry.json"

# Category key → proper PascalCase enum name
ENUM_NAMES = {
    "bancode": "BANcode",
    "warncode": "WARNcode",
    "comcode": "COMcode",
    "softcode": "SOFTcode",
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_registry():
    if not REGISTRY.exists():
        print(f"ERROR: {REGISTRY} not found. Run parse_sources.py first.", file=sys.stderr)
        sys.exit(1)
    with open(REGISTRY, "r", encoding="utf-8") as f:
        return json.load(f)


def c_name(hex_val, name):
    """Sanitise a codename for use as a C enum/define constant."""
    return f"BANCODE_{name}"


def rust_name(name):
    """Sanitise a codename for Rust enum variant."""
    return name


# ---------------------------------------------------------------------------
# C99 Freestanding Generation
# ---------------------------------------------------------------------------

def generate_c99(registry):
    inc_dir = ROOT / "kernel_inc" / "bancode"
    src_dir = ROOT / "kernel_src" / "bancode"
    inc_dir.mkdir(parents=True, exist_ok=True)
    src_dir.mkdir(parents=True, exist_ok=True)

    slots = registry["slots"]
    assigned = [s for s in slots if s["assigned"]]
    categories = registry["categories"]

    # --- bancode.h (master header) ---
    h = []
    h.append("/* bancode_all.h - BANcode Framework master header */")
    h.append("/* AUTO-GENERATED by generate_bindings.py - DO NOT EDIT */")
    h.append("#ifndef BANCODE_ALL_H")
    h.append("#define BANCODE_ALL_H")
    h.append("")
    h.append("#include <stdint.h>")
    h.append("#include <stdbool.h>")
    h.append("#include <stddef.h>")
    h.append("")
    h.append("typedef uint32_t bancode_t;")
    h.append("")
    h.append("#define BANCODE_VERSION_MAJOR 1")
    h.append("#define BANCODE_VERSION_MINOR 0")
    h.append("#define BANCODE_VERSION_PATCH 0")
    h.append("")

    # Block ranges
    for cat, meta in categories.items():
        tag = cat.upper()
        h.append(f"#define BANCODE_{tag}_START  0x{meta['block_start']}U")
        h.append(f"#define BANCODE_{tag}_END    0x{meta['block_end']}U")
    h.append("")

    # Subcategory ranges
    for cat, meta in categories.items():
        tag = cat.upper()
        for sc in meta.get("subcategories", []):
            sc_tag = re.sub(r"[^A-Z0-9]+", "_", sc["name"].upper()).strip("_")
            h.append(f"#define BANCODE_{tag}_{sc_tag}_START  0x{sc['start']}U")
            h.append(f"#define BANCODE_{tag}_{sc_tag}_END    0x{sc['end']}U")
    h.append("")

    # Forward-declare per-category headers
    for cat in categories:
        h.append(f"#include \"{cat}.h\"")
    h.append("")

    # Count unique assigned codes across all categories
    seen_names = set()
    for s in assigned:
        seen_names.add(s['name'])
    h.append(f"#define BANCODE_TOTAL_ASSIGNED {len(seen_names)}")
    h.append("")

    # Trap range dispatch (surrogate-pair style: 0x7FFFFFF0-0x7FFFFFFE maps 1:1 to BANcodes)
    h.append("/* Trap range dispatch - like Unicode surrogate pairs */")
    h.append("/* Each trap address 0x7FFFFFF0+N maps to BANcode at offset N */")
    h.append("#define BANCODE_TRAP_RANGE_START  0x7FFFFFF0U")
    h.append("#define BANCODE_TRAP_RANGE_END    0x7FFFFFFEU")
    h.append("#define BANCODE_TRAP_RANGE_COUNT  15U")
    h.append("")
    h.append("/* Convert trap address to BANcode offset (0-based within trap range) */")
    h.append("#define BANCODE_TRAP_TO_OFFSET(trap_addr)  ((trap_addr) - BANCODE_TRAP_RANGE_START)")
    h.append("")
    h.append("/* Convert trap offset to BANcode value (adds bancode block base) */")
    h.append("#define BANCODE_OFFSET_TO_CODE(offset)  (0x0011A000U + (offset))")
    h.append("")
    h.append("/* Convert trap address directly to BANcode value */")
    h.append("#define BANCODE_TRAP_TO_CODE(trap_addr)  (BANCODE_OFFSET_TO_CODE(BANCODE_TRAP_TO_OFFSET(trap_addr)))")
    h.append("")
    h.append("/* Returns true if address is within the trap dispatch range */")
    h.append("#define BANCODE_IS_TRAP_RANGE(addr)  ((addr) >= BANCODE_TRAP_RANGE_START && (addr) <= BANCODE_TRAP_RANGE_END)")
    h.append("")

    # Lookup function declarations
    h.append("/* Returns true if code is a known BANcode */")
    h.append("bool bancode_is_valid(bancode_t code);")
    h.append("")
    h.append("/* Returns codename string (\"UNKNOWN\" if not assigned) */")
    h.append("const char* bancode_name(bancode_t code);")
    h.append("")
    h.append("/* Returns description string (\"\" if not assigned) */")
    h.append("const char* bancode_desc(bancode_t code);")
    h.append("")
    h.append("/* Returns category string (\"\" if not assigned) */")
    h.append("const char* bancode_category(bancode_t code);")
    h.append("")
    h.append("#endif /* BANCODE_ALL_H */")

    with open(inc_dir / "bancode_all.h", "w", encoding="utf-8") as f:
        f.write("\n".join(h) + "\n")

    # --- Per-category headers (global dedup across all categories) ---
    global_seen = set()
    for cat, meta in categories.items():
        cat_slots = [s for s in slots if s["category"] == cat and s["assigned"]]
        # Deduplicate by name globally
        unique_cat = []
        for s in cat_slots:
            if s['name'] not in global_seen:
                global_seen.add(s['name'])
                unique_cat.append(s)
        tag = cat.upper()

        ch = []
        ch.append(f"/* {cat}.h - BANcode {cat} codes */")
        ch.append(f"/* AUTO-GENERATED - DO NOT EDIT */")
        ch.append(f"#ifndef BANCODE_{tag}_H")
        ch.append(f"#define BANCODE_{tag}_H")
        ch.append("")
        ch.append("#include <stdint.h>")
        ch.append("")
        ch.append(f"/* {meta.get('role', '')} */")
        ch.append(f"/* Range: 0x{meta['block_start']} - 0x{meta['block_end']} */")
        ch.append("")

        ch.append(f"typedef enum bancode_{cat}_e {{")
        for s in unique_cat:
            ch.append(f"    {c_name(s['hex'], s['name'])} = 0x{s['hex']}U,")
        ch.append(f"}} bancode_{cat}_e;")
        ch.append("")
        ch.append(f"#endif /* BANCODE_{tag}_H */")

        with open(inc_dir / f"{cat}.h", "w", encoding="utf-8") as f:
            f.write("\n".join(ch) + "\n")

    # --- bancode.c (implementation) ---
    c = []
    c.append("/* bancode.c - BANcode Framework implementation */")
    c.append("/* AUTO-GENERATED by generate_bindings.py - DO NOT EDIT */")
    c.append("")
    c.append("#include \"bancode/bancode_all.h\"")
    c.append("")

    # Lookup table struct
    c.append("typedef struct bancode_entry {")
    c.append("    bancode_t code;")
    c.append("    const char* name;")
    c.append("    const char* desc;")
    c.append("    const char* category;")
    c.append("} bancode_entry;")
    c.append("")

    # Static lookup table
    c.append("static const bancode_entry bancode_table[] = {")
    for s in assigned:
        name_esc = s["name"].replace("\\", "\\\\").replace('"', '\\"')
        desc_esc = s["description"].replace("\\", "\\\\").replace('"', '\\"')
        c.append(f'    {{ 0x{s["hex"]}U, "{name_esc}", "{desc_esc}", "{s["category"]}" }},')
    c.append("};")
    c.append(f"#define BANCODE_TABLE_SIZE {len(assigned)}")
    c.append("")

    # Binary search helper
    c.append("static const bancode_entry* bancode_find(bancode_t code) {")
    c.append("    int lo = 0;")
    c.append("    int hi = (int)BANCODE_TABLE_SIZE - 1;")
    c.append("    while (lo <= hi) {")
    c.append("        int mid = lo + (hi - lo) / 2;")
    c.append("        if (bancode_table[mid].code == code) return &bancode_table[mid];")
    c.append("        if (bancode_table[mid].code < code) lo = mid + 1;")
    c.append("        else hi = mid - 1;")
    c.append("    }")
    c.append("    return (const bancode_entry*)0;")
    c.append("}")
    c.append("")

    # Public API
    c.append("bool bancode_is_valid(bancode_t code) {")
    c.append("    return bancode_find(code) != (const bancode_entry*)0;")
    c.append("}")
    c.append("")

    c.append("const char* bancode_name(bancode_t code) {")
    c.append("    const bancode_entry* e = bancode_find(code);")
    c.append('    return e ? e->name : "UNKNOWN";')
    c.append("}")
    c.append("")

    c.append("const char* bancode_desc(bancode_t code) {")
    c.append("    const bancode_entry* e = bancode_find(code);")
    c.append('    return e ? e->desc : "";')
    c.append("}")
    c.append("")

    c.append("const char* bancode_category(bancode_t code) {")
    c.append("    const bancode_entry* e = bancode_find(code);")
    c.append('    return e ? e->category : "";')
    c.append("}")

    with open(src_dir / "bancode.c", "w", encoding="utf-8") as f:
        f.write("\n".join(c) + "\n")

    print(f"Generated C99 headers in {inc_dir}")
    print(f"Generated C99 source in {src_dir}")
    print(f"  {len(assigned)} codes in lookup table")


# ---------------------------------------------------------------------------
# Rust Generation
# ---------------------------------------------------------------------------

def generate_rust(registry):
    rust_dir = ROOT / "rust_bindings"
    src_dir = rust_dir / "src"
    src_dir.mkdir(parents=True, exist_ok=True)

    slots = registry["slots"]
    assigned = [s for s in slots if s["assigned"]]
    categories = registry["categories"]

    # --- lib.rs ---
    rs = []
    rs.append("//! BANcode Framework - Rust bindings")
    rs.append("//! AUTO-GENERATED by generate_bindings.py - DO NOT EDIT")
    rs.append("")
    rs.append("#![no_std]")
    rs.append("")
    rs.append("use core::fmt;")
    rs.append("")

    # Per-category enums
    for cat, meta in categories.items():
        cat_slots = [s for s in slots if s["category"] == cat and s["assigned"]]
        enum_name = ENUM_NAMES[cat]
        seen_names = set()
        unique_slots = []
        for s in cat_slots:
            if s["name"] not in seen_names:
                seen_names.add(s["name"])
                unique_slots.append(s)

        rs.append(f"/// {meta.get('role', '')}")
        rs.append(f"/// Range: 0x{meta['block_start']} - 0x{meta['block_end']}")
        rs.append(f"#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]")
        rs.append(f"#[repr(u32)]")
        rs.append(f"pub enum {enum_name} {{")
        for s in unique_slots:
            variant = s["name"]
            rs.append(f"    {variant} = 0x{s['hex']},")
        rs.append("}")
        rs.append("")

        # Display impl
        rs.append(f"impl fmt::Display for {enum_name} {{")
        rs.append(f"    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {{")
        rs.append(f"        match *self {{")
        for s in unique_slots:
            rs.append(f"            {enum_name}::{s['name']} => write!(f, \"0x{s['hex']}: {s['name']}\"),")
        rs.append(f"        }}")
        rs.append(f"    }}")
        rs.append(f"}}")
        rs.append("")

        # TryFrom<u32>
        rs.append(f"impl TryFrom<u32> for {enum_name} {{")
        rs.append(f"    type Error = u32;")
        rs.append(f"    fn try_from(v: u32) -> Result<Self, u32> {{")
        rs.append(f"    match v {{")
        for s in unique_slots:
            rs.append(f"            0x{s['hex']} => Ok({enum_name}::{s['name']}),")
        rs.append(f"            _ => Err(v),")
        rs.append(f"        }}")
        rs.append(f"    }}")
        rs.append(f"}}")
        rs.append("")

    # Master enum
    rs.append("/// All BANcode diagnostic codes")
    rs.append("#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]")
    rs.append("#[repr(u32)]")
    rs.append("pub enum BANcode {")
    seen_names = set()
    unique_assigned = []
    for s in assigned:
        if s["name"] not in seen_names:
            seen_names.add(s["name"])
            unique_assigned.append(s)
            rs.append(f"    {s['name']} = 0x{s['hex']},")
    rs.append("}")
    rs.append("")

    # Display for master
    rs.append("impl fmt::Display for BANcode {")
    rs.append("    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {")
    rs.append("    match *self {")
    for s in unique_assigned:
        rs.append(f"            BANcode::{s['name']} => write!(f, \"0x{s['hex']}: {s['name']}\"),")
    rs.append("        }")
    rs.append("    }")
    rs.append("}")
    rs.append("")

    # TryFrom for master
    rs.append("impl TryFrom<u32> for BANcode {")
    rs.append("    type Error = u32;")
    rs.append("    fn try_from(v: u32) -> Result<Self, u32> {")
    rs.append("        match v {")
    for s in unique_assigned:
        rs.append(f"            0x{s['hex']} => Ok(BANcode::{s['name']}),")
    rs.append("            _ => Err(v),")
    rs.append("        }")
    rs.append("    }")
    rs.append("}")
    rs.append("")

    # Lookup functions
    rs.append("/// Returns true if code is a known BANcode")
    rs.append("pub fn is_valid(code: u32) -> bool {")
    rs.append("    BANcode::try_from(code).is_ok()")
    rs.append("}")
    rs.append("")
    rs.append("/// Returns codename string if known")
    rs.append("pub fn name(code: u32) -> Option<&'static str> {")
    rs.append("    match code {")
    for s in assigned:
        rs.append(f"        0x{s['hex']} => Some(\"{s['name']}\"),")
    rs.append("        _ => None,")
    rs.append("    }")
    rs.append("}")

    with open(src_dir / "lib.rs", "w", encoding="utf-8") as f:
        f.write("\n".join(rs) + "\n")

    # --- Cargo.toml ---
    cargo = []
    cargo.append("[package]")
    cargo.append('name = "bancode"')
    cargo.append('version = "0.1.0"')
    cargo.append('edition = "2026"')
    cargo.append('description = "BANcode Framework - diagnostic code bindings"')
    cargo.append("")
    cargo.append("[lib]")
    cargo.append('name = "bancode"')
    cargo.append('path = "src/lib.rs"')

    with open(rust_dir / "Cargo.toml", "w", encoding="utf-8") as f:
        f.write("\n".join(cargo) + "\n")

    print(f"Generated Rust crate in {rust_dir}")
    print(f"  {len(assigned)} codes across {len(categories)} enums")


# ---------------------------------------------------------------------------
# Python Generation
# ---------------------------------------------------------------------------

def generate_python(registry):
    py_dir = ROOT / "python" / "bancode"
    py_dir.mkdir(parents=True, exist_ok=True)

    slots = registry["slots"]
    assigned = [s for s in slots if s["assigned"]]
    categories = registry["categories"]

    # --- __init__.py ---
    init = []
    init.append('"""BANcode Framework - Python bindings"""')
    init.append("")
    init.append("from bancode.registry import BANcodeRegistry")
    for cat in categories:
        init.append(f"from bancode.{cat} import {ENUM_NAMES[cat]}")
    init.append("")
    init.append("__all__ = [")
    init.append('    "BANcodeRegistry",')
    for cat in categories:
        init.append(f'    "{ENUM_NAMES[cat]}",')
    init.append("]")
    init.append("")

    with open(py_dir / "__init__.py", "w", encoding="utf-8") as f:
        f.write("\n".join(init) + "\n")

    # --- Per-category enums ---
    for cat, meta in categories.items():
        cat_slots = [s for s in slots if s["category"] == cat and s["assigned"]]
        enum_name = ENUM_NAMES[cat]

        ce = []
        ce.append(f'"""BANcode {cat} codes"""')
        ce.append("")
        ce.append("from enum import IntEnum")
        ce.append("")
        ce.append(f"class {enum_name}(IntEnum):")
        ce.append(f'    """{meta.get("role", "")}"""')
        ce.append("")
        seen_names = set()
        for s in cat_slots:
            if s["name"] in seen_names:
                continue
            seen_names.add(s["name"])
            ce.append(f'    {s["name"]} = 0x{s["hex"]}')
        ce.append("")
        ce.append("    @classmethod")
        ce.append("    def from_value(cls, val):")
        ce.append("        try:")
        ce.append("            return cls(val)")
        ce.append("        except ValueError:")
        ce.append("            return None")
        ce.append("")

        with open(py_dir / f"{cat}.py", "w", encoding="utf-8") as f:
            f.write("\n".join(ce) + "\n")

    # --- registry.py ---
    reg = []
    reg.append('"""BANcode master registry lookup."""')
    reg.append("")
    reg.append("from dataclasses import dataclass")
    reg.append("from typing import Optional")
    for cat in categories:
        reg.append(f"from bancode.{cat} import {ENUM_NAMES[cat]}")
    reg.append("")
    reg.append("")
    reg.append("@dataclass")
    reg.append("class CodeEntry:")
    reg.append('    """Complete metadata for a single BANcode."""')
    reg.append("    hex_value: str")
    reg.append("    value: int")
    reg.append("    name: str")
    reg.append("    category: str")
    reg.append("    subcategory: str")
    reg.append("    description: str")
    reg.append("")
    reg.append("")
    reg.append("class BANcodeRegistry:")
    reg.append('    """Singleton registry for all BANcode codes."""')
    reg.append("")
    reg.append("    _instance = None")
    reg.append("    _codes = {}")
    reg.append("")
    reg.append("    def __new__(cls):")
    reg.append("        if cls._instance is None:")
    reg.append("            cls._instance = super().__new__(cls)")
    reg.append("            cls._instance._load()")
    reg.append("        return cls._instance")
    reg.append("")
    reg.append("    def _load(self):")
    reg.append("        codes = {")
    for s in assigned:
        desc = s["description"].replace('"', '\\"')
        reg.append(f'            0x{s["hex"]}: CodeEntry(')
        reg.append(f'                hex_value="0x{s["hex"]}",')
        reg.append(f'                value=0x{s["hex"]},')
        reg.append(f'                name="{s["name"]}",')
        reg.append(f'                category="{s["category"]}",')
        reg.append(f'                subcategory="{s["subcategory"]}",')
        reg.append(f'                description="{desc}",')
        reg.append(f'            ),')
    reg.append("        }")
    reg.append("        self._codes = codes")
    reg.append("")
    reg.append("    def lookup(self, code):")
    reg.append('        """Look up a code by int value. Returns CodeEntry or None."""')
    reg.append("        return self._codes.get(code)")
    reg.append("")
    reg.append("    def name(self, code):")
    reg.append('        """Return codename string or \'UNKNOWN\'."""')
    reg.append("        entry = self._codes.get(code)")
    reg.append('        return entry.name if entry else "UNKNOWN"')
    reg.append("")
    reg.append("    def is_valid(self, code):")
    reg.append('        """Return True if code is a known BANcode."""')
    reg.append("        return code in self._codes")
    reg.append("")
    reg.append("    @property")
    reg.append("    def all_codes(self):")
    reg.append("        return list(self._codes.values())")

    with open(py_dir / "registry.py", "w", encoding="utf-8") as f:
        f.write("\n".join(reg) + "\n")

    print(f"Generated Python package in {py_dir}")
    print(f"  {len(assigned)} codes across {len(categories)} enums")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    registry = load_registry()
    generate_c99(registry)
    generate_rust(registry)
    generate_python(registry)
    print("All bindings generated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
